# Verified by eye from labelled composites R_Txx.png. Q1 time-on (any), Q2 assessment time (up to 3), Q3 info wanted (any),
# Q4 missed classes (any), Q5 lesson planning (any), Q6 one workflow (any)
T = {}
T[1] = dict(  # faint grey circles on Q1 'Marking' and 'Tracking curriculum' counted
    q1=['Marking student work', 'Organizing teaching materials', 'Tracking curriculum/topic coverage'],
    q2=['Creating questions', 'Marking', 'Identifying learning gaps', 'Recording grades'],
    q3=['Students who are improving', 'Class performance compared with previous assessments', 'Curriculum/topic coverage', 'Individual performance', 'Students needing support'],
    q4=['Automatically identify what the student missed', 'Provide lesson notes/materials', 'Give a catch-up quiz', 'Recommend what the student should do next', 'Provide practice activities', "Show the student's progress after catching up"],
    q5=['Lesson-plan templates', 'Different activities for different ability levels', 'Track what has already been taught', 'Curriculum-aligned lesson resources', 'Activities and examples for lessons', 'Share/reuse resources with other teachers'],
    q6=['Question creation', 'Exam formatting', 'Automatic marking', 'Grade calculation', 'Performance analysis', 'Identifying learning gaps'])
T[2] = dict(
    q1=['Creating exams/tests', 'Marking student work', 'Identifying students who need help', 'Organizing teaching materials', 'Tracking student performance', 'Creating lesson plans', 'Generating reports'],
    q2=['Creating questions', 'Marking'],
    q3=['Performance by topic', 'Students who are improving', 'Students who are struggling', 'Common mistakes', 'Students needing support'],
    q4=['Provide lesson notes/materials', 'Give a catch-up quiz', 'Provide practice activities', "Show the student's progress after catching up"],
    q5=['AI-assisted lesson planning', 'Different activities for different ability levels', 'Curriculum-aligned lesson resources', 'Activities and examples for lessons'],
    q6=['Question creation', 'Teacher marking', 'Result release', 'Automatic marking', 'Grade calculation', 'Performance analysis'])
T[3] = dict(
    q1=['Creating exams/tests', 'Organizing teaching materials', 'Managing attendance', 'Managing classes', 'Creating lesson plans', 'Communicating with students'],
    q2=['Marking', 'Calculating results'],
    q3=['Overall performance', 'Students who are improving', 'Class performance compared with previous assessments', 'Individual performance', 'Students who are struggling', 'Common mistakes', 'Attendance', 'Students needing support'],
    q4=['Automatically identify what the student missed', 'Provide lesson notes/materials', 'Recommend what the student should do next', "Show the student's progress after catching up"],
    q5=['AI-assisted lesson planning', 'Different activities for different ability levels', 'Track what has already been taught', 'Curriculum-aligned lesson resources', 'Easy access to previous lessons/resources'],
    q6=['Question creation', 'Teacher marking', 'Result release', 'Exam formatting', 'Grade calculation', 'Identifying learning gaps'])
T[4] = dict(  # light ticks; Q3 'Class performance' uncertain, counted. Q2 has 5 ticks (limit 3).
    q1=['Creating exams/tests', 'Marking student work', 'Organizing teaching materials'],
    q2=['Creating questions', 'Marking', 'Calculating results', 'Recording grades', 'Analyzing performance'],
    q3=['Performance by topic', 'Students who are improving', 'Class performance compared with previous assessments', 'Common mistakes', 'Students needing support'],
    q4=['Automatically identify what the student missed', 'Provide lesson notes/materials', 'Give a catch-up quiz', 'Provide practice activities', "Show the student's progress after catching up"],
    q5=['Lesson-plan templates', 'AI-assisted lesson planning', 'Different activities for different ability levels', 'Curriculum-aligned lesson resources', 'Activities and examples for lessons', 'Easy access to previous lessons/resources'],
    q6=['Question creation', 'Teacher marking', 'Exam formatting', 'Grade calculation', 'Performance analysis'])
T[5] = dict(  # very faint blue pencil ticks: moderate confidence
    q1=['Creating exams/tests', 'Managing attendance', 'Creating assignments', 'Tracking student performance', 'Creating lesson plans', 'Communicating with students'],
    q2=['Creating questions', 'Marking', 'Analyzing performance'],
    q3=['Overall performance', 'Students who are improving', 'Students who are struggling', 'Attendance'],
    q4=['Automatically identify what the student missed', 'Give a catch-up quiz', 'Provide missed lessons', "Show the student's progress after catching up"],
    q5=['Lesson-plan templates', 'AI-assisted lesson planning', 'Track what has already been taught', 'Activities and examples for lessons'],
    q6=['Question creation', 'Result release', 'Automatic marking', 'Grade calculation'])
T[6] = dict(  # black circles; Q1 ticked 8 of 12 options
    q1=['Creating exams/tests', 'Identifying students who need help', 'Organizing teaching materials', 'Managing attendance', 'Tracking student performance', 'Creating lesson plans', 'Tracking curriculum/topic coverage', 'Generating reports'],
    q2=['Creating questions', 'Marking', 'Formatting exams'],
    q3=['Performance by topic', 'Students who are improving', 'Curriculum/topic coverage', 'Individual performance', 'Students who are struggling', 'Common mistakes', 'Attendance', 'Students needing support'],
    q4=['Automatically identify what the student missed', 'Provide lesson notes/materials', 'Provide missed lessons', 'Provide practice activities', "Show the student's progress after catching up"],
    q5=['AI-assisted lesson planning', 'Different activities for different ability levels', 'Track what has already been taught', 'Curriculum-aligned lesson resources', 'Activities and examples for lessons', 'Easy access to previous lessons/resources', 'Share/reuse resources with other teachers'],
    q6=['Question creation', 'Teacher marking', 'Result release', 'Exam formatting', 'Automatic marking', 'Grade calculation', 'Performance analysis', 'Identifying learning gaps'])
T[7] = dict(
    q1=['Identifying students who need help'],
    q2=['Identifying learning gaps', 'Analyzing performance'],
    q3=['Class performance compared with previous assessments', 'Individual performance', 'Students who are struggling', 'Common mistakes'],
    q4=['Automatically identify what the student missed', 'Provide missed lessons', "Show the student's progress after catching up"],
    q5=['AI-assisted lesson planning', 'Different activities for different ability levels'],
    q6=['Question creation'])
T[8] = dict(  # slash through nearly every option on Q1 and Q4 (flag); Q2 has 6 ticks (limit 3)
    q1=['Creating exams/tests', 'Marking student work', 'Identifying students who need help', 'Organizing teaching materials', 'Managing attendance', 'Managing classes', 'Creating assignments', 'Tracking student performance', 'Creating lesson plans', 'Tracking curriculum/topic coverage', 'Communicating with students', 'Generating reports'],
    q2=['Marking', 'Calculating results', 'Formatting exams', 'Recording grades', 'Analyzing performance', 'Preparing reports'],
    q3=['Performance by topic', 'Class performance compared with previous assessments', 'Students who are struggling', 'Common mistakes', 'Students needing support'],
    q4=['Automatically identify what the student missed', 'Provide lesson notes/materials', 'Give a catch-up quiz', 'Recommend what the student should do next', 'Provide missed lessons', 'Provide practice activities', "Show the student's progress after catching up"],
    q5=['AI-assisted lesson planning', 'Different activities for different ability levels', 'Curriculum-aligned lesson resources', 'Activities and examples for lessons', 'Share/reuse resources with other teachers'],
    q6=['Printing/exporting', 'Teacher marking', 'Exam formatting', 'Automatic marking', 'Grade calculation', 'Performance analysis'])
T[9] = dict(
    q1=['Creating exams/tests', 'Identifying students who need help', 'Managing attendance', 'Tracking student performance', 'Creating lesson plans', 'Communicating with students', 'Generating reports'],
    q2=['Creating questions', 'Calculating results', 'Analyzing performance'],
    q3=['Overall performance', 'Class performance compared with previous assessments', 'Students who are struggling', 'Common mistakes'],
    q4=['Automatically identify what the student missed', 'Provide lesson notes/materials', 'Provide missed lessons'],
    q5=['Lesson-plan templates', 'Different activities for different ability levels', 'Curriculum-aligned lesson resources', 'Activities and examples for lessons', 'Share/reuse resources with other teachers'],
    q6=['Question creation', 'Reports', 'Performance analysis', 'Identifying learning gaps'])
T[10] = dict(
    q1=['Marking student work', 'Organizing teaching materials'],
    q2=['Marking'],
    q3=['Students who are struggling', 'Students needing support'],
    q4=['Automatically identify what the student missed', 'Provide lesson notes/materials', "Show the student's progress after catching up"],
    q5=['AI-assisted lesson planning', 'Different activities for different ability levels', 'Activities and examples for lessons', 'Share/reuse resources with other teachers'],
    q6=['Teacher marking', 'Online delivery', 'Grade calculation', 'Performance analysis'])
