# Verified by eye from labelled composites R_Sxx.png. Only circled/ticked boxes are recorded.
# Q1 uses (any), Q2 difficult topic (up to 3), Q3 catch-up (select ONE), Q4 practice (up to 3), Q5 progress (any)
S = {}
S[1] = dict(
    q1=['Catching up when I miss class'],
    q2=['Study at my own pace'],
    q3=['Everything I need to catch up'],
    q4=['Short quizzes'],
    q5=['Topics I need to improve'])
S[2] = dict(
    q1=['Studying/preparing for exams', 'Catching up when I miss class', 'Communicating with teachers', 'Accessing notes/learning materials'],
    q2=['Step-by-step explanations', 'Practice questions', 'Games/challenges', 'Examples'],
    q3=['Lesson/notes', 'Everything I need to catch up', 'Video explanation', 'Practice questions'],
    q4=['Games/competitions', 'Practice based on topics I struggle with', 'Flashcards'],
    q5=['Grades', 'Topics I need to improve', 'Study recommendations', 'Strongest subjects/topics'])
S[3] = dict(
    q1=['Studying/preparing for exams', 'Understanding difficult topics', 'Seeing grades/progress', 'Organizing schoolwork'],
    q2=['Step-by-step explanations', 'Practice questions', 'Games/challenges', 'Personalized study recommendations', 'Quizzes', 'Study at my own pace'],
    q3=['Lesson/notes', 'Interactive lesson', 'Quiz', 'Video explanation', 'Practice questions'],
    q4=['Short quizzes', 'Games/competitions', 'Flashcards'],
    q5=[])
S[4] = dict(
    q1=['Studying/preparing for exams', 'Practice questions', 'Seeing grades/progress'],
    q2=['Step-by-step explanations', 'Practice questions', 'Quizzes'],
    q3=['Video explanation'],
    q4=['Traditional practice questions', 'Timed practice exams', 'Adaptive/harder questions'],
    q5=['Topics I need to improve', 'Compare with my previous performance'])
S[5] = dict(  # black slash ticks; ticked almost everything on Q1 and Q5 (flag)
    q1=['Studying/preparing for exams', 'Tracking tests/deadlines', 'Catching up when I miss class', 'Communicating with teachers', 'Practice questions'],
    q2=['Step-by-step explanations', 'Videos', 'Study at my own pace'],
    q3=['Lesson/notes'],
    q4=['Games/competitions', 'Timed practice exams', 'Flashcards'],
    q5=['Grades', 'Topics I need to improve', 'Upcoming assessments', 'Study recommendations', 'Attendance', 'Strongest subjects/topics', 'Compare with my previous performance', 'Completed assignments', 'Progress toward goals'])
S[6] = dict(
    q1=['Studying/preparing for exams', 'Catching up when I miss class', 'Practice questions', 'Understanding difficult topics'],
    q2=['Step-by-step explanations', 'Practice questions', 'Quizzes'],
    q3=['Lesson/notes', 'Quiz', 'Digital/AI tutor'],
    q4=['Short quizzes', 'Practice based on topics I struggle with', 'Immediate explanations when I get an answer wrong', 'Flashcards'],
    q5=['Grades', 'Topics I need to improve', 'Compare with my previous performance', 'Progress toward goals'])
S[7] = dict(
    q1=[], q1_other='everything',
    q2=['Step-by-step explanations'],
    q3=['Interactive lesson'],
    q4=['Short quizzes'],
    q5=[])
S[8] = dict(  # X drawn over 'Traditional practice questions' counted as a selection (could be a cross-out)
    q1=['Studying/preparing for exams', 'Practice questions', 'Understanding difficult topics'],
    q2=['Step-by-step explanations', 'Practice questions', 'Quizzes'],
    q3=['Video explanation'],
    q4=['Traditional practice questions', 'Timed practice exams', 'Practice based on topics I struggle with', 'Adaptive/harder questions'],
    q5=['Topics I need to improve', 'Progress toward goals'])
S[9] = dict(
    q1=['Studying/preparing for exams', 'Tracking tests/deadlines', 'Accessing notes/learning materials'],
    q2=['Step-by-step explanations', 'Games/challenges', 'Videos', 'Examples'],
    q3=['Lesson/notes', 'Interactive lesson', 'Practice questions'],
    q4=['Short quizzes', 'Timed practice exams', 'Immediate explanations when I get an answer wrong'],
    q5=['Grades', 'Topics I need to improve', 'Strongest subjects/topics', 'Progress toward goals'])
S[10] = dict(
    q1=['Studying/preparing for exams', 'Practice questions', 'Organizing schoolwork'],
    q2=['Step-by-step explanations', 'Practice questions', 'Quizzes'],
    q3=['Everything I need to catch up', 'Digital/AI tutor'],
    q4=['Flashcards'],
    q5=['Grades', 'Compare with my previous performance'])
S[11] = dict(  # faint circle on 'Practice based on topics I struggle with' counted
    q1=['Studying/preparing for exams', 'Practice questions', 'Understanding difficult topics'],
    q2=['Step-by-step explanations', 'Practice questions', 'Quizzes'],
    q3=['Video explanation'],
    q4=['Short quizzes', 'Practice based on topics I struggle with', 'Flashcards', 'Adaptive/harder questions'],
    q5=['Grades', 'Topics I need to improve', 'Study recommendations', 'Strongest subjects/topics', 'Compare with my previous performance', 'Completed assignments', 'Progress toward goals'])
S[12] = dict(  # Interactive lesson (Q3) looked uncertain and was not counted
    q1=['Studying/preparing for exams', 'Tracking tests/deadlines', 'Accessing notes/learning materials', 'Seeing grades/progress'],
    q2=['Step-by-step explanations', 'Games/challenges', 'Instant feedback when I get something wrong', 'Examples'],
    q3=['Lesson/notes', 'Quiz', 'Digital/AI tutor'],
    q4=['Games/competitions', 'Flashcards', 'Challenges against classmates', 'Immediate explanations when I get an answer wrong'],
    q5=['Grades', 'Topics I need to improve', 'Upcoming assessments', 'Strongest subjects/topics', 'Compare with my previous performance'])
