#!/bin/bash
# Joins the parts into the one file you run: scripts/demo/manchester-demo-seed.sql (and the remove file).
cd "$(dirname "$0")"
{ echo "-- Manchester demo data seed (generated by build.sh; edit the files in parts/, not this one)."
  echo "-- Safe to run again: it first removes what an earlier run added."
  echo "begin;"
  cat parts/00-remove.sql parts/10-assess.sql parts/11-assess-results.sql parts/12-assess-responses.sql
  ls parts/[234]*.sql >/dev/null 2>&1 && cat parts/[234]*.sql
  echo "commit;"
  echo "select 'Demo data added' as result;"; } > manchester-demo-seed.sql
{ echo "begin;"; cat parts/00-remove.sql; echo "commit;"; echo "select 'Demo data removed' as result;"; } > manchester-demo-remove.sql
wc -l manchester-demo-seed.sql manchester-demo-remove.sql
