-- Manchester demo data seed (generated by build.sh; edit the files in parts/, not this one).
-- Safe to run again: it first removes what an earlier run added.
begin;
-- Removes everything an earlier run of the Manchester demo seed added (rows whose id starts with dd000000-).
-- It does NOT undo: moving Testing Student into the demo class and setting them to Grade 9, or the Testing Teacher's class link.
create or replace function pg_temp.is_demo(u uuid) returns boolean language sql immutable as $$ select u::text like 'dd000000-%' $$;

delete from marking_point_responses where response_id in (select r.id from responses r join exam_sessions s on s.id = r.session_id where pg_temp.is_demo(s.id));
delete from responses where session_id in (select id from exam_sessions where pg_temp.is_demo(id));
delete from exam_sessions where pg_temp.is_demo(id);
delete from final_exam_questions where pg_temp.is_demo(final_exam_id);
delete from final_exam_class_groups where pg_temp.is_demo(final_exam_id);
update draft_exams set published_final_exam_id = null where pg_temp.is_demo(id);
delete from final_exams where pg_temp.is_demo(id);
delete from questions where pg_temp.is_demo(draft_exam_id);
delete from draft_exam_class_groups where pg_temp.is_demo(draft_exam_id);
delete from draft_exams where pg_temp.is_demo(id);

-- learning part
delete from department_resources where pg_temp.is_demo(id);
delete from lesson_plans where pg_temp.is_demo(id);
delete from flashcards where pg_temp.is_demo(deck_id);
delete from flashcard_decks where pg_temp.is_demo(id);
delete from learning_check_attempts where pg_temp.is_demo(lesson_id);
delete from learning_progress where pg_temp.is_demo(lesson_id);
delete from learning_check_questions where pg_temp.is_demo(lesson_id);
delete from learning_assignments where pg_temp.is_demo(lesson_id);
delete from learning_lessons where pg_temp.is_demo(id);

-- demo topics (only if nothing real uses them), and the morning-register rows the seed marked for the demo class
delete from curriculum_topics ct where pg_temp.is_demo(ct.id)
  and not exists (select 1 from questions q where q.topic_id = ct.id)
  and not exists (select 1 from learning_lessons l where l.topic_id = ct.id)
  and not exists (select 1 from lesson_plans p where p.topic_id = ct.id)
  and not exists (select 1 from department_resources r where r.topic_id = ct.id);
delete from daily_attendance da
where da.marked_by = (select id from profiles where full_name = 'Testing Teacher' and role = 'teacher' limit 1)
  and da.att_date >= current_date - 30
  and da.student_id in (select e.student_id from enrollments e where e.class_group_id in
        (select tcg.class_group_id from teacher_class_groups tcg where tcg.teacher_id = (select id from profiles where full_name = 'Testing Teacher' and role = 'teacher' limit 1)));
-- ====================== ASSESS: topics, tests, questions, results ======================
create or replace function pg_temp.did(n int) returns uuid language sql immutable as $$ select ('dd000000-0000-4000-8000-' || lpad(n::text, 12, '0'))::uuid $$;
create or replace function pg_temp.rnd(k text) returns numeric language sql immutable as $$ select (abs(hashtextextended(k, 7)) % 10000) / 10000.0 $$;
-- the last weekday on or before (today minus n days), so no test is dated on a weekend
create or replace function pg_temp.wk(n int) returns date language sql stable as $$
  select case extract(dow from (current_date - n)) when 0 then current_date - n - 2 when 6 then current_date - n - 1 else current_date - n end $$;

create temp table demo_ctx (teacher uuid, hod uuid, principal uuid, student uuid, dept uuid, class_id uuid, class_name text);

do $$
declare
  v_teacher uuid; v_hod uuid; v_principal uuid; v_student uuid; v_dept uuid; v_class uuid; v_class_name text; v_n int;
begin
  select id, department_id into v_teacher, v_dept from profiles where full_name = 'Testing Teacher' and role = 'teacher' limit 1;
  select id into v_hod from profiles where full_name = 'Testing HOD' and role = 'supervisor' limit 1;
  select id into v_principal from profiles where full_name = 'Testing Principal' and role = 'principal' limit 1;
  select id into v_student from profiles where student_id = '54321' and role = 'student' limit 1;
  if v_teacher is null then raise exception 'Cannot find the account named Testing Teacher (role teacher)'; end if;
  if v_hod is null then raise exception 'Cannot find the account named Testing HOD (role supervisor)'; end if;
  if v_principal is null then raise exception 'Cannot find the account named Testing Principal (role principal)'; end if;
  if v_student is null then raise exception 'Cannot find the student with ID 54321'; end if;
  if v_dept is null then raise exception 'Testing Teacher has no department'; end if;

  -- the demo class: the Grade 9 class with the most students (the test student joins it)
  select cg.id, cg.name into v_class, v_class_name
  from class_groups cg left join enrollments e on e.class_group_id = cg.id
  where cg.year_grade = 'Grade 9' and cg.department_id = v_dept
  group by cg.id, cg.name order by count(e.id) desc, cg.name limit 1;
  if v_class is null then raise exception 'There is no Grade 9 class in the teacher''s department'; end if;

  -- Testing Student: Grade 9, in the demo class only
  update profiles set grade_level = 9 where id = v_student;
  delete from enrollments where student_id = v_student and class_group_id <> v_class;
  insert into enrollments (student_id, class_group_id) values (v_student, v_class) on conflict do nothing;
  -- Testing Teacher teaches the demo class and Mathematics
  insert into teacher_class_groups (teacher_id, class_group_id) values (v_teacher, v_class) on conflict do nothing;
  insert into teacher_subjects (teacher_id, department_id, subject)
    select v_teacher, v_dept, 'Mathematics' where not exists (select 1 from teacher_subjects where teacher_id = v_teacher and subject = 'Mathematics');
  update profiles set department_id = v_dept where id = v_hod and department_id is null;
  insert into department_subjects (department_id, subject) select v_dept, 'Mathematics' where not exists (select 1 from department_subjects where department_id = v_dept and lower(btrim(subject)) = 'mathematics');

  select count(*) into v_n from enrollments where class_group_id = v_class;
  if v_n < 12 then raise exception 'The demo class % has only % students; need at least 12', v_class_name, v_n; end if;
  insert into demo_ctx values (v_teacher, v_hod, v_principal, v_student, v_dept, v_class, v_class_name);
end $$;

-- Grade 9 Mathematics topics (added only if missing)
insert into curriculum_topics (id, code, subject, grade, unit, name, status, sort_order)
select pg_temp.did(100 + t.n), '', 'Mathematics', 9, t.unit, t.name, 'active', t.n
from (values
  (1, 'Consumer arithmetic', 'Simple interest'), (2, 'Consumer arithmetic', 'Compound interest'),
  (3, 'Ratio and proportion', 'Direct and inverse variation'), (4, 'Ratio and proportion', 'Compound ratios and rates'),
  (5, 'Algebra', 'Expanding and factorising expressions'), (6, 'Algebra', 'Solving quadratic equations'), (7, 'Algebra', 'Simultaneous linear equations'),
  (8, 'Geometry', 'Pythagoras'' theorem'), (9, 'Coordinate geometry and graphs', 'Equation of a straight line')
) as t(n, unit, name)
where not exists (select 1 from curriculum_topics c where lower(btrim(c.subject)) = 'mathematics' and c.grade = 9 and lower(btrim(c.name)) = lower(btrim(t.name)) and c.status <> 'archived');

-- ---- the tests ----
-- test_no, title, kind, days ago, duration
create temp table demo_tests as select * from (values
  (1, 'Pop Quiz: Simple Interest',                    'pop_quiz',    42, 20),
  (2, 'Weekly Test: Algebra',                         'weekly_test', 35, 30),
  (3, 'Class Test: Ratio and Variation',              'class_test',  28, 35),
  (4, 'Class Test: Pythagoras and Straight Lines',    'class_test',  21, 35),
  (5, 'Monthly Test: Interest and Equations',         'monthly',     10, 45)
) as t(test_no, title, kind, days_ago, duration);

-- test_no, order, type, question, options, correct answer, most common wrong answer, topic
create temp table demo_q (test_no int, ord int, qtype text, qtext text, opts jsonb, correct text, wrong text, topic text);
insert into demo_q values
 (1,1,'multiple_choice','Find the simple interest on $2000 at 5% per year for 3 years.','["$100","$300","$315","$600"]','$300','$315','Simple interest'),
 (1,2,'multiple_choice','Simple interest of $90 is earned on $600 at 3% per year. For how many years?','["3 years","4 years","5 years","6 years"]','5 years','3 years','Simple interest'),
 (1,3,'multiple_choice','Which is the formula for simple interest?','["I = PRT/100","I = P(1 + R)^T","I = P + R + T","I = P/RT"]','I = PRT/100','I = P(1 + R)^T','Simple interest'),
 (1,4,'multiple_choice','A loan of $5000 at 4% simple interest for 2 years. How much is repaid in total?','["$400","$5400","$5416","$5800"]','$5400','$400','Simple interest'),
 (1,5,'true_false','Simple interest is calculated on the original amount only.','["True","False"]','True','False','Simple interest'),
 (1,6,'short_answer','Find the simple interest on $1500 at 6% for 2 years (number only).',null,'180',null,'Simple interest'),
 (1,7,'multiple_choice','What is the simple interest on $800 for 18 months at 5% per year?','["$40","$60","$80","$720"]','$60','$720','Simple interest'),
 (1,8,'multiple_choice','At what rate per year does $400 earn $48 simple interest in 3 years?','["3%","4%","12%","16%"]','4%','12%','Simple interest'),
 (2,1,'multiple_choice','Expand 3(x + 4).','["3x + 4","3x + 12","x + 12","3x + 7"]','3x + 12','3x + 4','Expanding and factorising expressions'),
 (2,2,'multiple_choice','Expand (x + 2)(x + 5).','["x² + 7x + 10","x² + 10","x² + 7x + 7","2x + 7"]','x² + 7x + 10','x² + 10','Expanding and factorising expressions'),
 (2,3,'multiple_choice','Factorise 6x + 9.','["3(2x + 3)","6(x + 9)","3(2x + 9)","9(x + 6)"]','3(2x + 3)','3(2x + 9)','Expanding and factorising expressions'),
 (2,4,'multiple_choice','Factorise x² + 5x + 6.','["(x + 2)(x + 3)","(x + 1)(x + 6)","(x + 5)(x + 1)","(x − 2)(x − 3)"]','(x + 2)(x + 3)','(x + 1)(x + 6)','Expanding and factorising expressions'),
 (2,5,'multiple_choice','Expand and simplify (x − 3)².','["x² − 9","x² − 6x + 9","x² + 9","x² − 3x + 9"]','x² − 6x + 9','x² − 9','Expanding and factorising expressions'),
 (2,6,'short_answer','What is the value of 3(x + 2) when x = 4? (number only)',null,'18',null,'Expanding and factorising expressions'),
 (2,7,'multiple_choice','Solve x + y = 10 and x − y = 2. What is x?','["4","6","8","12"]','6','4','Simultaneous linear equations'),
 (2,8,'multiple_choice','For the same equations, what is y?','["2","4","6","8"]','4','6','Simultaneous linear equations'),
 (2,9,'multiple_choice','Solve 2x + y = 11 and x + y = 7. What is x?','["3","4","5","7"]','4','3','Simultaneous linear equations'),
 (2,10,'true_false','A pair of simultaneous linear equations can have exactly one solution.','["True","False"]','True','False','Simultaneous linear equations'),
 (3,1,'multiple_choice','y varies directly with x. When x = 2, y = 10. Find y when x = 5.','["20","25","30","50"]','25','20','Direct and inverse variation'),
 (3,2,'multiple_choice','4 workers finish a job in 6 days. How long will 8 workers take, working at the same rate?','["12 days","3 days","2 days","4 days"]','3 days','12 days','Direct and inverse variation'),
 (3,3,'multiple_choice','Which is an example of direct variation?','["Cost of 5 patties at a fixed price each","Time to travel 100 km as speed increases","Workers and days to finish a job","Brightness and distance from a lamp"]','Cost of 5 patties at a fixed price each','Time to travel 100 km as speed increases','Direct and inverse variation'),
 (3,4,'true_false','In inverse variation, when one quantity doubles the other halves.','["True","False"]','True','False','Direct and inverse variation'),
 (3,5,'multiple_choice','y varies inversely with x and y = 6 when x = 4. Find y when x = 3.','["6","8","12","18"]','8','12','Direct and inverse variation'),
 (3,6,'short_answer','y varies directly with x and y = 12 when x = 3. Find y when x = 7 (number only).',null,'28',null,'Direct and inverse variation'),
 (3,7,'multiple_choice','A car uses 8 litres of fuel per 100 km. How many litres for 250 km?','["16","20","25","32"]','20','25','Compound ratios and rates'),
 (3,8,'multiple_choice','Share $120 in the ratio 3 : 2. What is the larger share?','["$48","$60","$72","$80"]','$72','$48','Compound ratios and rates'),
 (3,9,'multiple_choice','A recipe uses flour and sugar in the ratio 5 : 2. With 300 g of flour, how much sugar is needed?','["60 g","120 g","150 g","750 g"]','120 g','750 g','Compound ratios and rates'),
 (3,10,'multiple_choice','Simplify the ratio 24 : 36.','["2 : 3","3 : 4","4 : 6","6 : 9"]','2 : 3','4 : 6','Compound ratios and rates'),
 (4,1,'multiple_choice','A right-angled triangle has legs of 3 cm and 4 cm. What is the hypotenuse?','["5 cm","7 cm","12 cm","25 cm"]','5 cm','7 cm','Pythagoras'' theorem'),
 (4,2,'multiple_choice','The hypotenuse is 13 cm and one leg is 5 cm. What is the other leg?','["8 cm","12 cm","18 cm","144 cm"]','12 cm','8 cm','Pythagoras'' theorem'),
 (4,3,'true_false','Pythagoras'' theorem applies to any triangle.','["True","False"]','False','True','Pythagoras'' theorem'),
 (4,4,'multiple_choice','Which set of side lengths forms a right-angled triangle?','["6, 8, 10","5, 6, 9","4, 5, 7","7, 8, 12"]','6, 8, 10','5, 6, 9','Pythagoras'' theorem'),
 (4,5,'short_answer','A right-angled triangle has legs of 6 cm and 8 cm. Find the hypotenuse in cm (number only).',null,'10',null,'Pythagoras'' theorem'),
 (4,6,'multiple_choice','What is the gradient of the line through (1, 2) and (3, 8)?','["2","3","4","6"]','3','2','Equation of a straight line'),
 (4,7,'multiple_choice','What is the y-intercept of y = 2x + 5?','["2","5","−5","7"]','5','2','Equation of a straight line'),
 (4,8,'multiple_choice','Which line is parallel to y = 3x + 1?','["y = 3x − 4","y = −3x + 1","y = x/3 + 1","y = 1 − 3x"]','y = 3x − 4','y = −3x + 1','Equation of a straight line'),
 (4,9,'true_false','The gradients of perpendicular lines multiply to −1.','["True","False"]','True','False','Equation of a straight line'),
 (4,10,'multiple_choice','What is the midpoint of (2, 4) and (6, 10)?','["(4, 7)","(8, 14)","(2, 3)","(4, 6)"]','(4, 7)','(8, 14)','Equation of a straight line'),
 (5,1,'multiple_choice','Find the simple interest on $3000 at 4% per year for 5 years.','["$120","$600","$650","$3600"]','$600','$650','Simple interest'),
 (5,2,'multiple_choice','Find the simple interest on $1200 at 5% per year for 6 months.','["$30","$60","$300","$360"]','$30','$60','Simple interest'),
 (5,3,'multiple_choice','$2500 earns $200 simple interest in 2 years. What is the yearly rate?','["2%","4%","8%","10%"]','4%','8%','Simple interest'),
 (5,4,'multiple_choice','Which is the formula for the amount A with compound interest?','["A = P(1 + r/100)^n","A = P + PRT","A = P × r × n","A = P/(1 + r)"]','A = P(1 + r/100)^n','A = P + PRT','Compound interest'),
 (5,5,'multiple_choice','$1000 is invested at 10% compound interest for 2 years. What is the final amount?','["$1100","$1200","$1210","$1220"]','$1210','$1200','Compound interest'),
 (5,6,'true_false','Over 2 or more years at the same rate, compound interest is always more than simple interest.','["True","False"]','True','False','Compound interest'),
 (5,7,'multiple_choice','Solve x² − 5x + 6 = 0.','["x = 2 or 3","x = −2 or −3","x = 1 or 6","x = 5 or 6"]','x = 2 or 3','x = −2 or −3','Solving quadratic equations'),
 (5,8,'multiple_choice','What are the solutions of x² = 49?','["x = 7","x = ±7","x = 24.5","x = 49"]','x = ±7','x = 7','Solving quadratic equations'),
 (5,9,'multiple_choice','Solve x² + 2x − 8 = 0.','["x = 2 or −4","x = −2 or 4","x = 1 or −8","x = 8 or −1"]','x = 2 or −4','x = −2 or 4','Solving quadratic equations'),
 (5,10,'short_answer','Find the discriminant of x² − 4x + 4 = 0 (number only).',null,'0',null,'Solving quadratic equations'),
 (5,11,'essay','Explain, with an example, how compound interest differs from simple interest.',null,null,null,'Compound interest');

-- topic difficulty (higher = harder for the class) so each topic ends up with a believable result
create temp table demo_topic_d as select * from (values
  ('Simple interest', .30), ('Compound interest', .25), ('Solving quadratic equations', .15), ('Direct and inverse variation', .05),
  ('Expanding and factorising expressions', -.02), ('Simultaneous linear equations', .05), ('Pythagoras'' theorem', -.12),
  ('Equation of a straight line', -.05), ('Compound ratios and rates', -.05)
) as t(topic, d);

-- test papers, links to the class, questions
insert into draft_exams (id, title, subject, created_by, instructions, status, created_at, submitted_at, reviewed_at, department_id, exam_kind,
                         direct_published, direct_published_at, duration_minutes, pass_mark, questions_per_page, target_grade, calculator_enabled, available_from, available_until)
select pg_temp.did(1000 + t.test_no), t.title, 'Mathematics', c.teacher, 'Show your working where asked. Calculators are allowed.', 'published',
       (pg_temp.wk(t.days_ago + 3))::timestamptz, null, null, c.dept, t.kind, true, (pg_temp.wk(t.days_ago) + time '09:00') at time zone 'America/Jamaica', t.duration, 50, 5, 9, true,
       (pg_temp.wk(t.days_ago) + time '09:00') at time zone 'America/Jamaica', (pg_temp.wk(t.days_ago) + time '16:00') at time zone 'America/Jamaica'
from demo_tests t cross join demo_ctx c;
insert into draft_exam_class_groups (draft_exam_id, class_group_id) select pg_temp.did(1000 + t.test_no), c.class_id from demo_tests t cross join demo_ctx c;

insert into questions (id, draft_exam_id, created_by, question_type, question_text, options, correct_answer, points, order_index, is_bank_question, topic_id, topic, essay_rubric, total_marks)
select pg_temp.did(2000 + q.test_no * 100 + q.ord), pg_temp.did(1000 + q.test_no), c.teacher, q.qtype, q.qtext, q.opts, q.correct,
       case when q.qtype = 'essay' then 4 else 1 end, q.ord, (q.test_no <= 4),
       (select id from curriculum_topics ct where lower(btrim(ct.subject)) = 'mathematics' and ct.grade = 9 and lower(btrim(ct.name)) = lower(btrim(q.topic)) and ct.status <> 'archived' order by ct.created_at limit 1),
       null,
       case when q.qtype = 'essay' then '[{"text":"States that simple interest is calculated on the original amount only","marks":1},{"text":"States that compound interest is calculated on the amount plus the interest already earned","marks":1},{"text":"Gives a correct worked example for one of the two","marks":1},{"text":"Compares the two results, or says which grows faster and why","marks":1}]'::jsonb end,
       null
from demo_q q cross join demo_ctx c;
-- ---- the HOD-vetted end-of-term exam (published to the class) and one exam waiting for the HOD ----
insert into draft_exams (id, title, subject, created_by, instructions, status, created_at, submitted_at, reviewed_by, reviewed_at, review_notes, department_id, exam_kind,
                         direct_published, duration_minutes, pass_mark, questions_per_page, target_grade, calculator_enabled, published_final_exam_id, available_from, available_until)
select pg_temp.did(1100), 'Term 1 Mathematics Examination', 'Mathematics', c.teacher, 'Answer all questions. Calculators are allowed.', 'published',
       (pg_temp.wk(24))::timestamptz, (pg_temp.wk(22))::timestamptz, c.hod, (pg_temp.wk(20))::timestamptz, 'Approved. Good spread of topics.', c.dept, 'end_of_term',
       false, 60, 50, 5, 9, true, null, (pg_temp.wk(14) + time '09:00') at time zone 'America/Jamaica', (pg_temp.wk(14) + time '16:00') at time zone 'America/Jamaica'
from demo_ctx c;
insert into final_exams (id, title, subject, instructions, created_by, status, duration_minutes, published_at, created_at, department_id, class_group_id, exam_category, pass_mark, questions_per_page, target_grade, calculator_enabled, available_from, available_until)
select pg_temp.did(1200), 'Term 1 Mathematics Examination', 'Mathematics', 'Answer all questions. Calculators are allowed.', c.teacher, 'published', 60,
       (pg_temp.wk(18))::timestamptz, (pg_temp.wk(20))::timestamptz, c.dept, c.class_id, 'end_of_term', 50, 5, 9, true,
       (pg_temp.wk(14) + time '09:00') at time zone 'America/Jamaica', (pg_temp.wk(14) + time '16:00') at time zone 'America/Jamaica'
from demo_ctx c;
update draft_exams set published_final_exam_id = pg_temp.did(1200) where id = pg_temp.did(1100);
insert into final_exam_class_groups (final_exam_id, class_group_id) select pg_temp.did(1200), class_id from demo_ctx;

-- 15 questions for the final, copied from the topics above, 2 marks each
create temp table demo_final_src (ord int, src_test int, src_ord int);
insert into demo_final_src values (1,1,1),(2,1,4),(3,2,2),(4,2,3),(5,2,7),(6,3,1),(7,3,2),(8,3,8),(9,4,1),(10,4,2),(11,4,6),(12,4,7),(13,4,10),(14,5,5),(15,5,7);
insert into questions (id, draft_exam_id, created_by, question_type, question_text, options, correct_answer, points, order_index, is_bank_question, topic_id, topic)
select pg_temp.did(3000 + f.ord), pg_temp.did(1100), q.created_by, q.question_type, q.question_text, q.options, q.correct_answer, 2, f.ord, false, q.topic_id, q.topic
from demo_final_src f join questions q on q.id = pg_temp.did(2000 + f.src_test * 100 + f.src_ord);
insert into final_exam_questions (final_exam_id, question_id, order_index) select pg_temp.did(1200), pg_temp.did(3000 + ord), ord from demo_final_src;

-- an exam the teacher has submitted and the HOD has not yet reviewed (so "vet and publish" can be shown live)
insert into draft_exams (id, title, subject, created_by, instructions, status, created_at, submitted_at, department_id, exam_kind, direct_published, duration_minutes, pass_mark, questions_per_page, target_grade, calculator_enabled)
select pg_temp.did(1300), 'Term 2 Mathematics Examination (draft for review)', 'Mathematics', c.teacher, 'Answer all questions.', 'submitted',
       (pg_temp.wk(3))::timestamptz, (pg_temp.wk(1))::timestamptz, c.dept, 'final_exam_submission', false, 60, 50, 5, 9, true
from demo_ctx c;
insert into questions (id, draft_exam_id, created_by, question_type, question_text, options, correct_answer, points, order_index, is_bank_question, topic_id, topic)
select pg_temp.did(3100 + f.ord), pg_temp.did(1300), q.created_by, q.question_type, q.question_text, q.options, q.correct_answer, 2, f.ord, false, q.topic_id, q.topic
from (values (1,2,5),(2,3,4),(3,4,4),(4,4,8),(5,5,4),(6,5,9)) as f(ord, src_test, src_ord)
join questions q on q.id = pg_temp.did(2000 + f.src_test * 100 + f.src_ord);

-- ---- students and how well each tends to do ----
create temp table demo_students as
select e.student_id as student, row_number() over (order by e.student_id) as idx,
       case when e.student_id = c.student then 0.50 else 0.38 + 0.52 * pg_temp.rnd(e.student_id::text) end as ability
from enrollments e cross join demo_ctx c where e.class_group_id = c.class_id;

-- ---- who sat what, when ----
create temp table demo_sit as
select s.student, s.idx, s.ability, t.test_no, null::int as final_no,
       pg_temp.did(5000 + t.test_no * 100 + s.idx::int) as session_id, pg_temp.did(1000 + t.test_no) as draft_id, null::uuid as final_id,
       (pg_temp.wk(t.days_ago) + time '10:15' + (s.idx * interval '20 seconds')) at time zone 'America/Jamaica' as started, t.duration, (t.test_no <= 4) as released
from demo_students s cross join demo_tests t cross join demo_ctx c
where s.student = c.student or pg_temp.rnd(s.student::text || t.test_no::text) > 0.07
union all
select s.student, s.idx, s.ability, null, 1, pg_temp.did(6000 + s.idx::int), null, pg_temp.did(1200),
       (pg_temp.wk(14) + time '09:20' + (s.idx * interval '25 seconds')) at time zone 'America/Jamaica', 60, true
from demo_students s cross join demo_ctx c
where s.student = c.student or pg_temp.rnd(s.student::text || 'final') > 0.05;

insert into exam_sessions (id, final_exam_id, draft_exam_id, student_id, status, started_at, completed_at, tab_switch_count, flagged, time_limit_seconds, results_released, option_shuffle_seed, password_verified, violation_log)
select x.session_id, x.final_id, x.draft_id, x.student, 'completed', x.started, x.started + (x.duration - 3 - floor(pg_temp.rnd(x.session_id::text) * 8)::int) * interval '1 minute',
       case when x.student <> c.student and pg_temp.rnd(x.session_id::text || 'tab') > 0.97 then 4 when x.student <> c.student and pg_temp.rnd(x.session_id::text || 'tab') > 0.92 then 1 else 0 end,
       (x.student <> c.student and pg_temp.rnd(x.session_id::text || 'tab') > 0.97),
       x.duration * 60, x.released, floor(pg_temp.rnd(x.session_id::text || 'seed') * 100000)::int, true, '[]'::jsonb
from demo_sit x cross join demo_ctx c;
update exam_sessions s set violation_log = (
  select jsonb_agg(jsonb_build_object('reason', 'Switched to another tab or window', 'timestamp', (s.started_at + (n * interval '4 minutes')), 'count', n)) from generate_series(1, s.tab_switch_count) n)
where pg_temp.is_demo(s.id) and s.tab_switch_count > 0;

-- ---- answers ----
create temp table demo_qinfo as
select pg_temp.did(2000 + q.test_no * 100 + q.ord) as question_id, q.wrong from demo_q q
union all
select pg_temp.did(3000 + f.ord), q.wrong from demo_final_src f join demo_q q on q.test_no = f.src_test and q.ord = f.src_ord;

create temp table demo_items as
select x.session_id, x.student, x.ability, q.id as question_id, q.question_type, q.options, q.correct_answer, q.points, q.order_index,
       coalesce(qi.wrong, '') as wrong, greatest(0.08, least(0.97, x.ability - coalesce(td.d, 0) + 0.14)) as p
from demo_sit x
join questions q on q.draft_exam_id = coalesce(x.draft_id, pg_temp.did(1100))
left join demo_qinfo qi on qi.question_id = q.id
left join curriculum_topics ct on ct.id = q.topic_id
left join demo_topic_d td on lower(td.topic) = lower(ct.name);

alter table demo_items add column is_right boolean, add column ans text;
update demo_items set is_right = pg_temp.rnd(session_id::text || question_id::text) < p where question_type <> 'essay';
update demo_items i set ans = case
    when question_type = 'essay' then null
    when is_right then correct_answer
    when question_type = 'short_answer' then (correct_answer::numeric + 10)::text
    when pg_temp.rnd(session_id::text || question_id::text || 'w') < 0.65 then wrong
    else coalesce((select o from jsonb_array_elements_text(i.options) o where o <> i.correct_answer and o <> i.wrong order by o limit 1), wrong)
  end;
-- essays on the monthly test: about half are marked, the rest wait for the teacher
alter table demo_items add column essay_marked boolean, add column essay_marks int;
update demo_items set essay_marked = pg_temp.rnd(session_id::text || 'marked') < 0.45,
                      essay_marks = greatest(1, least(4, round(ability * 4 + (pg_temp.rnd(session_id::text || 'em') - 0.5))::int))
where question_type = 'essay';

insert into responses (session_id, question_id, answer, points_awarded, graded_by, graded_at)
select i.session_id, i.question_id,
       case when i.question_type = 'essay' then
         (array[
           'Simple interest is worked out on the money you start with, so it stays the same every year. Compound interest is worked out on the money plus the interest already added, so it grows faster. For example, $1000 at 10% for 2 years gives $200 simple interest but $210 compound interest.',
           'With simple interest you only earn on the original amount. With compound interest you earn interest on the interest too. Compound interest is better for savings.',
           'Compound interest is when the bank adds the interest and then charges again on it. Simple interest is just the interest. I think compound is bigger.'
         ])[1 + floor(pg_temp.rnd(i.session_id::text || 'txt') * 3)::int]
       else i.ans end,
       case when i.question_type = 'essay' then (case when i.essay_marked then i.essay_marks end)
            when i.is_right then i.points else 0 end,
       case when i.question_type = 'essay' then (case when i.essay_marked then (select teacher from demo_ctx) end) end,
       case when i.question_type = 'essay' and i.essay_marked then now() - interval '2 days' end
from demo_items i;

-- marking points on the marked essays: the first N of 4 points earned
insert into marking_point_responses (response_id, point_index, points_awarded, graded_by, graded_at)
select r.id, p.n - 1, case when p.n <= r.points_awarded then 1 else 0 end, r.graded_by, r.graded_at
from responses r join demo_items i on i.session_id = r.session_id and i.question_id = r.question_id and i.question_type = 'essay' and i.essay_marked
cross join generate_series(1, 4) p(n);

-- totals
update exam_sessions s set
  total_score = t.got, max_possible_score = t.maxp,
  fully_graded = not exists (select 1 from responses r join questions q on q.id = r.question_id where r.session_id = s.id and q.question_type = 'essay' and r.points_awarded is null)
from (select r.session_id, sum(coalesce(r.points_awarded, 0)) as got, sum(q.points) as maxp from responses r join questions q on q.id = r.question_id group by r.session_id) t
where t.session_id = s.id and pg_temp.is_demo(s.id);
-- ====================== LEARNING: lessons, checks, progress, catch-up, flashcards, plans, resources ======================
-- Removal of this part is added to 00-remove.sql (see the bottom of that file).

create temp table demo_lessons (n int, title text, grade int, topic text, key_terms text, steps jsonb);
insert into demo_lessons values
 (1, 'Simple Interest: Earning Money on Money You Save', 9, 'Simple interest',
  E'Principal (P): the money you start with\nRate (R): the percentage paid each year\nTime (T): the number of years\nSimple interest: I = PRT/100',
  jsonb_build_array(
   jsonb_build_object('key','engage','approved',true,'resources','[]'::jsonb,'text',E'Imagine you save $2000 in a credit union that pays 5% a year. After 3 years, how much extra money do you think you would have? Take a guess before you read on and write it down.\n\nWe will check your guess at the end of the lesson.'),
   jsonb_build_object('key','explore','approved',true,'resources','[]'::jsonb,'text',E'Work out the interest earned in one year on $2000 at 5%. Hint: 5% means 5 out of every 100.\n\nNow work out the interest for 2 years, then 3 years. What pattern do you see?'),
   jsonb_build_object('key','explain','approved',true,'resources','[]'::jsonb,'text',E'Simple interest is calculated on the original amount only, so the same interest is added every year.\n\nI = PRT / 100, where P is the principal, R is the yearly rate (%) and T is the time in years.\n\nWorked example: P = $2000, R = 5, T = 3.\nI = 2000 × 5 × 3 / 100 = $300.\nTotal amount = $2000 + $300 = $2300.'),
   jsonb_build_object('key','elaborate','approved',true,'resources','[]'::jsonb,'text',E'1. Find the simple interest on $1500 at 6% for 2 years.\n2. A loan of $800 at 5% simple interest is repaid after 18 months. How much is repaid in total?\n3. $400 earns $48 in 3 years. Find the rate.'),
   jsonb_build_object('key','evaluate','approved',true,'resources','[]'::jsonb,'text',E'Go back to your guess from the start. How close were you? Write one sentence explaining what simple interest means in your own words, then try the check questions.'))),
 (2, 'Expanding and Factorising Expressions', 9, 'Expanding and factorising expressions',
  E'Expand: multiply out brackets\nFactorise: write as a product with brackets\nCommon factor: a number or letter that divides every term\nBinomial: an expression with two terms',
  jsonb_build_array(
   jsonb_build_object('key','engage','approved',true,'resources','[]'::jsonb,'text',E'A school orders 5 boxes of pens. Each box holds (2p + 3) pens, where p is an unknown pack size. How many pens in total? Think about what happens when you multiply a number by everything inside a bracket.'),
   jsonb_build_object('key','explore','approved',true,'resources','[]'::jsonb,'text',E'Draw a rectangle that is (x + 3) long and 2 wide. Split it into two parts and find each area. Add them. What do you notice about 2(x + 3) and 2x + 6?'),
   jsonb_build_object('key','explain','approved',true,'resources','[]'::jsonb,'text',E'Expanding: multiply the outside term by every term inside the bracket. 3(x + 4) = 3x + 12.\n\nTwo brackets: (x + 2)(x + 5) = x² + 5x + 2x + 10 = x² + 7x + 10.\n\nFactorising is expanding in reverse: find the common factor. 6x + 9 = 3(2x + 3).'),
   jsonb_build_object('key','elaborate','approved',true,'resources','[]'::jsonb,'text',E'Expand: 4(x − 2), (x + 3)(x + 4), (x − 1)(x + 6).\nFactorise: 10x + 15, x² + 7x + 12.'),
   jsonb_build_object('key','evaluate','approved',true,'resources','[]'::jsonb,'text',E'Pick one expression you expanded and factorise your answer to get back to the start. Explain why that works. Then try the check questions.'))),
 (3, 'Pythagoras'' Theorem', 9, 'Pythagoras'' theorem',
  E'Right-angled triangle: has one angle of 90 degrees\nHypotenuse: the longest side, opposite the right angle\nLegs: the two shorter sides\nPythagorean triple: whole numbers that fit a² + b² = c²',
  jsonb_build_array(
   jsonb_build_object('key','engage','approved',true,'resources','[]'::jsonb,'text',E'A ladder 5 m long leans against a wall with its foot 3 m from the wall. How high up the wall does it reach? Sketch it and guess before you read on.'),
   jsonb_build_object('key','explore','approved',true,'resources','[]'::jsonb,'text',E'On squared paper draw a right-angled triangle with legs 3 and 4. Draw a square on each side and count the small squares. What is special about the two smaller squares and the biggest one?'),
   jsonb_build_object('key','explain','approved',true,'resources','[]'::jsonb,'text',E'In a right-angled triangle, the square on the hypotenuse equals the sum of the squares on the other two sides: a² + b² = c².\n\nExample: legs 6 and 8. c² = 36 + 64 = 100, so c = 10.\n\nFinding a leg: subtract. If c = 13 and a = 5, then b² = 169 − 25 = 144, so b = 12.'),
   jsonb_build_object('key','elaborate','approved',true,'resources','[]'::jsonb,'text',E'1. Legs 9 and 12: find the hypotenuse.\n2. Hypotenuse 17, one leg 8: find the other leg.\n3. Is a triangle with sides 7, 24 and 25 right-angled? Show why.'),
   jsonb_build_object('key','evaluate','approved',true,'resources','[]'::jsonb,'text',E'Return to the ladder. Work out the height and check it against your guess. Then try the check questions.')));

insert into learning_lessons (id, teacher_id, title, subject, grade, topic_id, key_terms, steps, status, published_at, created_at, updated_at)
select pg_temp.did(7000 + l.n), c.teacher, l.title, 'Mathematics', l.grade,
       (select id from curriculum_topics ct where lower(btrim(ct.subject)) = 'mathematics' and ct.grade = 9 and lower(btrim(ct.name)) = lower(btrim(l.topic)) and ct.status <> 'archived' order by ct.created_at limit 1),
       l.key_terms, l.steps, 'published', (pg_temp.wk(45 - l.n * 12))::timestamptz, (pg_temp.wk(48 - l.n * 12))::timestamptz, (pg_temp.wk(45 - l.n * 12))::timestamptz
from demo_lessons l cross join demo_ctx c;

-- assignments: lesson 1 closed (due long ago, a few unfinished), lesson 2 open with a catch-up, lesson 3 upcoming
insert into learning_assignments (id, lesson_id, class_group_id, assigned_by, due_date, keep_open, created_at, taught_on)
select pg_temp.did(7100 + x.n), pg_temp.did(7000 + x.n), c.class_id, c.teacher, x.due, false, x.created, x.taught
from demo_ctx c cross join (values (1, pg_temp.wk(24), (pg_temp.wk(33))::timestamptz, pg_temp.wk(34)), (2, current_date + 5, (pg_temp.wk(10))::timestamptz, pg_temp.wk(9)), (3, current_date + 6, (pg_temp.wk(1))::timestamptz, null::date)) as x(n, due, created, taught);

-- the day lesson 2 was taught, four students (including Testing Student) were away: they get the catch-up
create temp table demo_away as
select s.student, s.idx from demo_students s cross join demo_ctx c
where s.student = c.student or s.idx in (3, 8, 14) order by (s.student = c.student) desc limit 4;

-- progress
create temp table demo_prog (lesson_n int, student uuid, steps text[], done boolean, ability numeric);
insert into demo_prog
select 1, s.student, case when pg_temp.rnd(s.student::text || 'p1') < 0.88 or s.student = c.student then array['engage','explore','explain','elaborate','evaluate'] else array['engage','explore'] end, null, s.ability
from demo_students s cross join demo_ctx c;
insert into demo_prog
select 2, s.student,
       case when s.student = c.student then array['engage']::text[]   -- away that day, has only just started the catch-up
            when s.student in (select student from demo_away) then null
            when pg_temp.rnd(s.student::text || 'p2') < 0.62 then array['engage','explore','explain','elaborate','evaluate']
            when pg_temp.rnd(s.student::text || 'p2') < 0.85 then array['engage','explore','explain'] else null end, null, s.ability
from demo_students s cross join demo_ctx c;
insert into demo_prog select 3, c.student, array['engage','explore'], null, 0.5 from demo_ctx c;
update demo_prog set done = (steps @> array['engage','explore','explain','elaborate','evaluate']);

insert into learning_progress (lesson_id, student_id, steps_done, started_at, last_activity_at, completed_at)
select pg_temp.did(7000 + p.lesson_n), p.student, p.steps,
       (pg_temp.wk(case p.lesson_n when 1 then 32 when 2 then 8 else 1 end) + time '14:05' + (pg_temp.rnd(p.student::text || p.lesson_n::text) * interval '5 hours')) at time zone 'America/Jamaica',
       (pg_temp.wk(case p.lesson_n when 1 then 30 when 2 then 6 else 1 end) + time '16:20') at time zone 'America/Jamaica',
       case when p.done then (pg_temp.wk(case p.lesson_n when 1 then 29 when 2 then 5 else 1 end) + time '16:20') at time zone 'America/Jamaica' end
from demo_prog p where p.steps is not null;

-- check questions, three levels per lesson
create temp table demo_cq (lesson_n int, level text, pos int, kind text, prompt text, opts jsonb, idx int, num numeric, expl text);
insert into demo_cq values
 (1,'support',1,'multiple_choice','In I = PRT/100, what does P stand for?','["Principal","Percentage","Payment","Period"]',0,null,'P is the principal: the money you start with.'),
 (1,'support',2,'numeric','What is the simple interest on $100 at 5% for 1 year?',null,null,5,'I = 100 × 5 × 1 / 100 = 5.'),
 (1,'core',1,'numeric','Find the simple interest on $2000 at 5% for 3 years.',null,null,300,'I = 2000 × 5 × 3 / 100 = 300.'),
 (1,'core',2,'numeric','Find the simple interest on $500 at 4% for 2 years.',null,null,40,'I = 500 × 4 × 2 / 100 = 40.'),
 (1,'core',3,'multiple_choice','$1000 is borrowed at 6% simple interest for 2 years. How much is repaid in total?','["$120","$1060","$1120","$1200"]',2,null,'Interest = 120, so total = 1000 + 120 = 1120.'),
 (1,'stretch',1,'numeric','A sum earns $144 simple interest in 3 years at 6% per year. Find the principal.',null,null,800,'P = 100 × I / (R × T) = 14400 / 18 = 800.'),
 (1,'stretch',2,'multiple_choice','Which has the bigger effect on simple interest?','["Doubling the principal","Doubling the rate","They have the same effect","Neither changes it"]',2,null,'Interest is proportional to both, so doubling either doubles the interest.'),
 (2,'support',1,'multiple_choice','Expand 2(x + 3).','["2x + 3","2x + 6","x + 6","2x + 5"]',1,null,'Multiply both terms by 2.'),
 (2,'support',2,'numeric','What is the value of 2(x + 3) when x = 1?',null,null,8,'2 × (1 + 3) = 8.'),
 (2,'core',1,'multiple_choice','Expand (x + 1)(x + 2).','["x² + 3x + 2","x² + 2","x² + 3x + 3","2x + 3"]',0,null,'x² + 2x + x + 2 = x² + 3x + 2.'),
 (2,'core',2,'multiple_choice','Factorise 4x + 8.','["4(x + 2)","2(x + 4)","4(x + 8)","x(4 + 8)"]',0,null,'4 is a common factor of 4x and 8.'),
 (2,'core',3,'numeric','What is (x + 3)(x + 4) when x = 2?',null,null,30,'5 × 6 = 30.'),
 (2,'stretch',1,'multiple_choice','Factorise x² − 9.','["(x − 3)(x + 3)","(x − 3)²","(x + 9)(x − 1)","x(x − 9)"]',0,null,'A difference of two squares.'),
 (2,'stretch',2,'numeric','A rectangle has area (x + 5)(x + 2). Find the area when x = 3.',null,null,40,'8 × 5 = 40.'),
 (3,'support',1,'multiple_choice','What is the longest side of a right-angled triangle called?','["Hypotenuse","Adjacent","Opposite","Base"]',0,null,'It is opposite the right angle.'),
 (3,'support',2,'numeric','What is 3² + 4²?',null,null,25,'9 + 16 = 25.'),
 (3,'core',1,'numeric','The legs are 5 and 12. Find the hypotenuse.',null,null,13,'25 + 144 = 169, and the square root of 169 is 13.'),
 (3,'core',2,'numeric','The hypotenuse is 10 and one leg is 6. Find the other leg.',null,null,8,'100 − 36 = 64, and the square root is 8.'),
 (3,'core',3,'multiple_choice','Which set is NOT a right-angled triangle?','["3, 4, 5","5, 12, 13","6, 8, 10","4, 5, 6"]',3,null,'16 + 25 = 41, which is not 36.'),
 (3,'stretch',1,'numeric','Find the length of the diagonal of a 9 by 12 rectangle.',null,null,15,'81 + 144 = 225, and the square root is 15.'),
 (3,'stretch',2,'multiple_choice','A 5 m ladder has its foot 3 m from a wall. How high does it reach?','["4 m","3 m","5 m","8 m"]',0,null,'25 − 9 = 16, and the square root is 4.');
insert into learning_check_questions (id, lesson_id, position, kind, prompt, options, correct_index, correct_number, tolerance, explanation, level)
select pg_temp.did(7200 + q.lesson_n * 20 + (case q.level when 'support' then 0 when 'core' then 5 else 10 end) + q.pos), pg_temp.did(7000 + q.lesson_n), q.pos, q.kind, q.prompt, q.opts, q.idx, q.num, case when q.kind = 'numeric' then 0 end, q.expl, q.level
from demo_cq q;

-- first attempts for students who finished lessons 1 and 2, at the level that suits them; a few tried again
insert into learning_check_attempts (lesson_id, student_id, attempt_no, answers, results, score, max_score, submitted_at, level)
select pg_temp.did(7000 + t.lesson_n), t.student, 1,
       jsonb_object_agg(t.qid::text, case when t.ok then (case when t.kind = 'multiple_choice' then t.idx::text else t.num::text end) else (case when t.kind = 'multiple_choice' then ((t.idx + 1) % 4)::text else (t.num + 1)::text end) end),
       jsonb_agg(jsonb_build_object('question_id', t.qid, 'correct', t.ok) order by t.pos),
       count(*) filter (where t.ok), count(*), max(t.at), max(t.level)
from (
  select p.lesson_n, p.student, q.kind, q.idx, q.num, q.pos, q.level, pg_temp.did(7200 + q.lesson_n * 20 + (case q.level when 'support' then 0 when 'core' then 5 else 10 end) + q.pos) as qid,
         pg_temp.rnd(p.student::text || q.lesson_n::text || q.level || q.pos::text) < greatest(0.1, least(0.95, p.ability + case q.level when 'support' then 0.25 when 'stretch' then -0.2 else 0 end)) as ok,
         (pg_temp.wk(case p.lesson_n when 1 then 29 else 5 end) + time '16:30') at time zone 'America/Jamaica' as at
  from demo_prog p
  join demo_cq q on q.lesson_n = p.lesson_n and q.level = (case when p.ability < 0.48 then 'support' when p.ability > 0.82 then 'stretch' else 'core' end)
  where p.done and p.lesson_n in (1, 2)
) t group by t.lesson_n, t.student;

-- ---- attendance (also drives the catch-up): two weeks of morning register ----
create temp table demo_days as select d::date as day from generate_series(current_date - 21, current_date, interval '1 day') d where extract(dow from d) between 1 and 5;
insert into daily_attendance (student_id, att_date, status, marked_by, marked_at)
select s.student, d.day,
       case when exists (select 1 from demo_away a where a.student = s.student) and d.day = pg_temp.wk(9) then 'absent'
            when pg_temp.rnd(s.student::text || d.day::text) < 0.035 then 'absent'
            when pg_temp.rnd(s.student::text || d.day::text || 'l') < 0.06 then 'late' else 'present' end,
       c.teacher, (d.day + time '08:20') at time zone 'America/Jamaica'
from demo_students s cross join demo_days d cross join demo_ctx c
where d.day <= current_date
on conflict (student_id, att_date) do update set status = excluded.status, marked_by = excluded.marked_by;

-- ---- flashcards for Testing Student ----
insert into flashcard_decks (id, student_id, title, subject, created_at, updated_at)
select pg_temp.did(7500 + x.n), c.student, x.title, 'Mathematics', now() - interval '12 days', now() - interval '1 day' from demo_ctx c cross join (values (1, 'Interest and Ratios'), (2, 'Pythagoras and Lines')) as x(n, title);
insert into flashcards (id, deck_id, front, back, box, due_at, times_seen, times_correct, last_reviewed_at, created_at)
select pg_temp.did(7600 + k.n), pg_temp.did(7500 + k.deck), k.front, k.back, k.box,
       case when k.due_in <= 0 then now() - interval '1 hour' else now() + (k.due_in * interval '1 day') end, k.seen, k.correct, now() - interval '2 days', now() - interval '12 days'
from (values
 (1,1,'What is the formula for simple interest?','I = PRT / 100, where P is the principal, R the yearly rate (%) and T the time in years.',2,0,4,2),
 (2,1,'What is the principal?','The money you start with (the amount borrowed or invested).',3,0,5,4),
 (3,1,'Simple interest on $2000 at 5% for 3 years?','$300',1,0,4,1),
 (4,1,'What is the compound interest formula for the amount?','A = P(1 + r/100)^n',1,0,3,1),
 (5,1,'How does compound interest differ from simple interest?','Compound interest is also earned on the interest already added, so it grows faster.',2,1,3,2),
 (6,1,'Share $120 in the ratio 3 : 2.','$72 and $48',4,3,6,6),
 (7,1,'Simplify 24 : 36.','2 : 3',4,4,5,5),
 (8,1,'What does direct variation mean?','When one quantity increases, the other increases in the same ratio (y = kx).',3,1,4,3),
 (9,1,'What does inverse variation mean?','When one quantity increases, the other decreases so that their product stays the same (xy = k).',2,0,3,1),
 (10,2,'State Pythagoras'' theorem.','In a right-angled triangle, a² + b² = c², where c is the hypotenuse.',3,2,5,4),
 (11,2,'Gradient of the line through (1, 2) and (3, 8)?','3',2,0,3,1),
 (12,2,'What is the y-intercept of y = mx + c?','c',5,5,6,6),
 (13,2,'What is the midpoint of (2, 4) and (6, 10)?','(4, 7)',1,0,2,0),
 (14,2,'Which side is the hypotenuse?','The longest side, opposite the right angle.',4,3,5,5)
) as k(n, deck, front, back, box, due_in, seen, correct);

-- ---- two lesson plans (private to the teacher) ----
insert into lesson_plans (id, teacher_id, subject, grade, term, unit_theme, focus_strand, topic, focus_question, duration, attainment_target, specific_objective, skills, prior_learning, materials, engage, explore, explain, elaborate, evaluate, success_criteria, published_to_library, topic_id)
select pg_temp.did(7800 + x.n), c.teacher, 'Mathematics', 'Grade 9', 'Term 1', x.unit, x.strand, x.topic, x.q, '40 minutes', x.at, x.obj, 'Reasoning, calculation, communication', x.prior, x.mat, x.eng, x.exp, x.expl, x.ela, x.ev, x.sc, false,
       (select id from curriculum_topics ct where lower(btrim(ct.subject)) = 'mathematics' and ct.grade = 9 and lower(btrim(ct.name)) = lower(btrim(x.topic)) and ct.status <> 'archived' order by ct.created_at limit 1)
from demo_ctx c cross join (values
 (1, 'Consumer arithmetic', 'Number', 'Simple interest', 'How much does saving or borrowing really cost?', 'Students apply percentages and formulae to money situations.', 'Calculate simple interest, principal, rate and time.', 'Percentages of a quantity; substitution into formulae.', 'Calculators, worksheet of real credit union rates, whiteboards.',
   'Show two savings offers and ask which pays more after 3 years.', 'Students work out the interest for 1, 2 and 3 years and look for the pattern.', 'Introduce I = PRT/100 with a worked example and a table.', 'Mixed problems: find the interest, the rate, the principal and the total repaid.', 'Exit ticket: three questions at support, core and stretch level.', 'I can use I = PRT/100 and rearrange it to find any one of the four values.'),
 (2, 'Algebra', 'Algebra', 'Expanding and factorising expressions', 'How are expanding and factorising related?', 'Students expand single and double brackets and factorise common factors.', 'Expand and factorise simple expressions.', 'Substitution; the distributive property.', 'Algebra tiles or squared paper, mini whiteboards.',
   'Area puzzle: a rectangle with sides x + 3 and 2.', 'Students split the rectangle and discover 2(x + 3) = 2x + 6.', 'Model expanding, then factorising as the reverse.', 'Matching cards: expressions and their expansions.', 'Five-question quiz, then a self-mark with the key.', 'I can expand a bracket and factorise by taking out a common factor.')
) as x(n, unit, strand, topic, q, at, obj, prior, mat, eng, exp, expl, ela, ev, sc);

-- ---- department resources: links the department shares ----
-- the pin rule checks who is signed in, so act as the head of department for these inserts (this lasts only for this transaction)
select set_config('request.jwt.claims', json_build_object('sub', (select hod::text from demo_ctx), 'role', 'authenticated')::text, true);
insert into department_resources (id, department_id, created_by, title, description, kind, url, subject, grade, topic_id, pinned, pinned_by, pinned_at, created_at, updated_at)
select pg_temp.did(7900 + x.n), c.dept, case when x.by_hod then c.hod else c.teacher end, x.title, x.descr, 'link', x.url, 'Mathematics', x.grade,
       (select id from curriculum_topics ct where lower(btrim(ct.subject)) = 'mathematics' and ct.grade = 9 and lower(btrim(ct.name)) = lower(btrim(x.topic)) and ct.status <> 'archived' order by ct.created_at limit 1),
       x.pin, case when x.pin then c.hod end, case when x.pin then now() - interval '3 days' end, now() - (x.n * interval '2 days'), now() - (x.n * interval '2 days')
from demo_ctx c cross join (values
 (1, 'Desmos graphing calculator', 'Free online graphing calculator. Good for straight lines and quadratics.', 'https://www.desmos.com/calculator', 9, 'Equation of a straight line', true, true),
 (2, 'GeoGebra Classic', 'Dynamic geometry: draw triangles and check Pythagoras'' theorem.', 'https://www.geogebra.org/classic', 9, 'Pythagoras'' theorem', false, false),
 (3, 'Math is Fun: Simple interest', 'A clear plain-language explanation with worked examples.', 'https://www.mathsisfun.com/money/simple-interest.html', 9, 'Simple interest', false, false),
 (4, 'NRICH: problem-solving tasks', 'Rich tasks for stretch groups.', 'https://nrich.maths.org/', 9, null, false, false),
 (5, 'Khan Academy: Algebra', 'Short videos and practice on expanding and factorising.', 'https://www.khanacademy.org/math/algebra', 9, 'Expanding and factorising expressions', false, true)
) as x(n, title, descr, url, grade, topic, pin, by_hod);
select set_config('request.jwt.claims', '', true);
commit;
select 'Demo data added' as result;
