import { b, log, session, admin } from './lib.mjs'
const [STUDENT, EXAM, PW, WAIT] = process.argv.slice(2)
const s = await session('student', `${STUDENT}@mhs.smartassess`)
await s.page.goto(`http://localhost:3000/student/direct-exam/${EXAM}`, { waitUntil: 'domcontentloaded', timeout: 180000 }); await s.page.waitForTimeout(6000); await s.skip()
await s.page.locator('input').first().fill(PW); await s.page.getByRole('button', { name: 'Unlock' }).click(); await s.page.waitForTimeout(3000)
await s.page.getByRole('button', { name: /Begin/i }).click(); await s.page.waitForSelector('text=Submit exam', { timeout: 180000 }); await s.page.waitForTimeout(2500)
await s.page.getByText('30', { exact: true }).first().click(); await s.page.waitForTimeout(500)
await s.page.getByText('$100', { exact: true }).first().click(); await s.page.waitForTimeout(500)
await s.page.getByText('3,4,5', { exact: true }).first().click(); await s.page.waitForTimeout(Number(WAIT) * 1000)
log(`answered 3, waited ${WAIT}s, reloading`); await s.page.reload({ waitUntil: 'domcontentloaded' }); await s.page.waitForSelector('text=Submit exam', { timeout: 120000 }); await s.page.waitForTimeout(3000)
log('after reload:', (await s.text()).match(/\d of 3 answered/)?.[0], '| ticked:', await s.page.locator('input[type=radio]:checked').count())
s.page.on('dialog', (d) => d.accept()); await s.page.getByRole('button', { name: /Submit exam/i }).click(); await s.page.waitForTimeout(2500); const c = s.page.getByRole('button', { name: /^Yes/i }); if (await c.count()) await c.last().click()
await s.page.waitForURL((u) => /submitted/.test(u.pathname), { timeout: 60000 }).catch(() => log('no submitted page')); log('submitted ->', new URL(s.page.url()).pathname, '| errors:', s.errs.join(' ; ') || 'none')
await admin.from('profiles').update({ active_login_token: null }).eq('student_id', STUDENT); await b.close()
